"use client"

import type { AssessmentState, ScoreResult } from "./types"

export async function generatePdfReport(
  state: AssessmentState,
  result: ScoreResult
): Promise<void> {
  const { default: jsPDF } = await import("jspdf")
  const { default: autoTable } = await import("jspdf-autotable")

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" })
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  const margin = 18
  const contentW = pageW - margin * 2

  const NAVY = [18, 30, 90] as [number, number, number]
  const BLUE = [37, 99, 235] as [number, number, number]
  const GREEN = [34, 197, 94] as [number, number, number]
  const AMBER = [245, 158, 11] as [number, number, number]
  const RED = [239, 68, 68] as [number, number, number]
  const LIGHT_GRAY = [248, 250, 252] as [number, number, number]
  const GRAY = [100, 116, 139] as [number, number, number]

  const maturityColor = (m: string): [number, number, number] => {
    switch (m) {
      case "Optimized": return GREEN
      case "Mature": return BLUE
      case "Developing": return AMBER
      default: return RED
    }
  }

  const scoreColor = (s: number): [number, number, number] => {
    if (s >= 86) return GREEN
    if (s >= 66) return BLUE
    if (s >= 41) return AMBER
    return RED
  }

  // ── Cover Page ──────────────────────────────────────────────────────────────
  doc.setFillColor(...NAVY)
  doc.rect(0, 0, pageW, 80, "F")

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(22)
  doc.setFont("helvetica", "bold")
  doc.text("DPDP Act 2023", margin, 32)
  doc.setFontSize(16)
  doc.setFont("helvetica", "normal")
  doc.text("Compliance Self-Assessment Report", margin, 42)

  doc.setFillColor(...BLUE)
  doc.rect(0, 80, pageW, 1.5, "F")

  doc.setTextColor(50, 50, 80)
  doc.setFontSize(11)
  doc.setFont("helvetica", "bold")
  doc.text("Organisation:", margin, 100)
  doc.setFont("helvetica", "normal")
  doc.text(state.companyName || "—", margin + 35, 100)

  doc.setFont("helvetica", "bold")
  doc.text("Assessor:", margin, 110)
  doc.setFont("helvetica", "normal")
  doc.text(state.assessorName || "—", margin + 35, 110)

  doc.setFont("helvetica", "bold")
  doc.text("Assessment Date:", margin, 120)
  doc.setFont("helvetica", "normal")
  doc.text(new Date(state.lastUpdatedAt).toLocaleDateString("en-IN", { dateStyle: "long" }), margin + 45, 120)

  // Score hero
  doc.setFillColor(...LIGHT_GRAY)
  doc.roundedRect(margin, 135, contentW, 52, 4, 4, "F")

  const sc = result.compositeScore
  const col = scoreColor(sc)
  doc.setFontSize(48)
  doc.setFont("helvetica", "bold")
  doc.setTextColor(...col)
  doc.text(`${sc}`, margin + 18, 170)
  doc.setFontSize(11)
  doc.setFont("helvetica", "normal")
  doc.setTextColor(...GRAY)
  doc.text("/ 100", margin + 45, 170)
  doc.text("Composite Compliance Score", margin + 18, 178)

  // Disclaimer box
  doc.setFillColor(255, 251, 235)
  doc.roundedRect(margin, 200, contentW, 28, 3, 3, "F")
  doc.setDrawColor(...AMBER)
  doc.roundedRect(margin, 200, contentW, 28, 3, 3, "S")
  doc.setFontSize(8)
  doc.setTextColor(120, 80, 0)
  doc.setFont("helvetica", "bold")
  doc.text("DISCLAIMER", margin + 4, 208)
  doc.setFont("helvetica", "normal")
  const disclaimer =
    "This report is a self-assessment aid and does not constitute legal advice. It is not a substitute for " +
    "a professional legal or compliance audit. Organisations should consult qualified privacy counsel before " +
    "making binding compliance decisions."
  const wrapped = doc.splitTextToSize(disclaimer, contentW - 8)
  doc.text(wrapped, margin + 4, 214)

  doc.setFontSize(8)
  doc.setTextColor(...GRAY)
  doc.text(
    `Generated by DPDP Self-Check • ${new Date().toLocaleDateString("en-IN")} • github.com/sahilsinghi/dpdp-compliance-tool`,
    pageW / 2, pageH - 10, { align: "center" }
  )

  // ── Executive Summary ───────────────────────────────────────────────────────
  doc.addPage()

  doc.setFillColor(...NAVY)
  doc.rect(0, 0, pageW, 20, "F")
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(13)
  doc.setFont("helvetica", "bold")
  doc.text("Executive Summary", margin, 13)

  let y = 30

  // Section maturity table
  doc.setFontSize(11)
  doc.setTextColor(50, 50, 80)
  doc.setFont("helvetica", "bold")
  doc.text("Section-by-Section Maturity Overview", margin, y)
  y += 6

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [["#", "Section", "Score", "Maturity", "Status"]],
    body: result.sectionScores.map((ss, i) => [
      String(i + 1),
      ss.sectionTitle,
      `${ss.score}%`,
      ss.maturity,
      `${ss.answeredCount}/${ss.totalCount} answered`,
    ]),
    headStyles: { fillColor: NAVY, textColor: [255, 255, 255], fontSize: 8, fontStyle: "bold" },
    bodyStyles: { fontSize: 8, textColor: [50, 50, 80] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: { 0: { cellWidth: 10 }, 2: { cellWidth: 20 }, 3: { cellWidth: 28 }, 4: { cellWidth: 36 } },
    didParseCell(data) {
      if (data.section === "body" && data.column.index === 3) {
        const maturity = data.cell.text[0]
        data.cell.styles.textColor = maturityColor(maturity)
        data.cell.styles.fontStyle = "bold"
      }
    },
  })

  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10

  // Scoring methodology note
  doc.setFillColor(...LIGHT_GRAY)
  doc.roundedRect(margin, y, contentW, 22, 3, 3, "F")
  doc.setFontSize(8)
  doc.setTextColor(80, 80, 100)
  doc.setFont("helvetica", "bold")
  doc.text("Scoring Methodology", margin + 4, y + 7)
  doc.setFont("helvetica", "normal")
  doc.text(
    "Composite score is a penalty-exposure weighted average of section scores. Section weights range from 3 (Applicability) to 10 (Security",
    margin + 4, y + 13
  )
  doc.text(
    "Safeguards) reflecting potential penalties under the DPDP Schedule. Yes=100%, Partial=50%, No=0%, N/A excluded from denominator.",
    margin + 4, y + 18
  )

  doc.setFontSize(8)
  doc.setTextColor(...GRAY)
  doc.text(
    `Generated by DPDP Self-Check • ${new Date().toLocaleDateString("en-IN")}`,
    pageW / 2, pageH - 10, { align: "center" }
  )

  // ── Top-10 Priority Gaps ─────────────────────────────────────────────────────
  doc.addPage()

  doc.setFillColor(...NAVY)
  doc.rect(0, 0, pageW, 20, "F")
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(13)
  doc.setFont("helvetica", "bold")
  doc.text("Top Priority Gaps & Remediation Roadmap", margin, 13)

  y = 30

  if (result.topGaps.length === 0) {
    doc.setTextColor(34, 197, 94)
    doc.setFontSize(14)
    doc.setFont("helvetica", "bold")
    doc.text("No high-priority gaps identified!", margin, y + 20)
    doc.setTextColor(...GRAY)
    doc.setFontSize(10)
    doc.setFont("helvetica", "normal")
    doc.text("All assessed areas are at or above the target compliance level.", margin, y + 30)
  } else {
    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [["#", "Section", "Gap Question", "Status", "Effort", "Max Penalty (INR Cr)", "Remediation Action"]],
      body: result.topGaps.map((gap, i) => [
        String(i + 1),
        gap.sectionTitle,
        gap.question,
        gap.response === "no" ? "Not Done" : "Partial",
        gap.effort,
        gap.penaltyExposure > 0 ? `Up to ${gap.penaltyExposure}` : "N/A",
        gap.remediationGuidance,
      ]),
      headStyles: { fillColor: NAVY, textColor: [255, 255, 255], fontSize: 7, fontStyle: "bold" },
      bodyStyles: { fontSize: 7, textColor: [50, 50, 80], overflow: "linebreak" },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      columnStyles: {
        0: { cellWidth: 8 },
        1: { cellWidth: 28 },
        2: { cellWidth: 40 },
        3: { cellWidth: 18 },
        4: { cellWidth: 15 },
        5: { cellWidth: 22 },
      },
      didParseCell(data) {
        if (data.section === "body" && data.column.index === 3) {
          data.cell.styles.textColor = data.cell.text[0] === "Not Done" ? RED : AMBER
          data.cell.styles.fontStyle = "bold"
        }
        if (data.section === "body" && data.column.index === 4) {
          if (data.cell.text[0] === "High") data.cell.styles.textColor = RED
          else if (data.cell.text[0] === "Medium") data.cell.styles.textColor = AMBER
          else data.cell.styles.textColor = GREEN
        }
      },
    })
  }

  doc.setFontSize(8)
  doc.setTextColor(...GRAY)
  doc.text(
    `Generated by DPDP Self-Check • ${new Date().toLocaleDateString("en-IN")}`,
    pageW / 2, pageH - 10, { align: "center" }
  )

  // ── Section-by-Section Detail ────────────────────────────────────────────────
  for (const ss of result.sectionScores) {
    doc.addPage()

    doc.setFillColor(...NAVY)
    doc.rect(0, 0, pageW, 20, "F")
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(11)
    doc.setFont("helvetica", "bold")
    doc.text(`Section: ${ss.sectionTitle}`, margin, 13)

    doc.setFillColor(...maturityColor(ss.maturity))
    doc.roundedRect(pageW - margin - 40, 4, 40, 12, 3, 3, "F")
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(9)
    doc.text(`${ss.maturity} • ${ss.score}%`, pageW - margin - 20, 12, { align: "center" })

    y = 28

    doc.setFontSize(8)
    doc.setTextColor(...GRAY)
    doc.text(`${ss.answeredCount} of ${ss.totalCount} questions answered • ${ss.naCount} marked N/A`, margin, y)
    y += 7

    doc.setFontSize(8)
    doc.setTextColor(...GRAY)
    doc.text(
      `Generated by DPDP Self-Check • ${new Date().toLocaleDateString("en-IN")}`,
      pageW / 2, pageH - 10, { align: "center" }
    )
  }

  // ── Save ─────────────────────────────────────────────────────────────────────
  const company = (state.companyName || "assessment").replace(/\s+/g, "-").toLowerCase()
  const date = new Date().toISOString().split("T")[0]
  doc.save(`dpdp-compliance-report-${company}-${date}.pdf`)
}
